# Generated by Django 4.2.7 on 2023-11-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_is_sub_category_scategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='scategories',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategories', to='home.category'),
        ),
    ]
